// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlR2TpMPSHlhRl4kU42vq0Fke3ATEaTI',
    appId: '1:512450300203:web:cd0b8b2215e613b25c5d6e',
    messagingSenderId: '512450300203',
    projectId: 'nhom4-ec8af',
    authDomain: 'nhom4-ec8af.firebaseapp.com',
    storageBucket: 'nhom4-ec8af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjAP9er0i9ggzZjzroGnWYn1Uusc3gQ4',
    appId: '1:512450300203:android:fc62c1955f4579055c5d6e',
    messagingSenderId: '512450300203',
    projectId: 'nhom4-ec8af',
    storageBucket: 'nhom4-ec8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUoBdjZmrT4C1h0gO0e5JhLgwv47B4V8',
    appId: '1:512450300203:ios:8c5ed91eabd953f85c5d6e',
    messagingSenderId: '512450300203',
    projectId: 'nhom4-ec8af',
    storageBucket: 'nhom4-ec8af.firebasestorage.app',
    androidClientId: '512450300203-n7qnqoso3hcm8cut4odu92428m202dtv.apps.googleusercontent.com',
    iosClientId: '512450300203-mf6nt69gc7lfch8shquhue5oltdchnqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhom4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUoBdjZmrT4C1h0gO0e5JhLgwv47B4V8',
    appId: '1:512450300203:ios:8c5ed91eabd953f85c5d6e',
    messagingSenderId: '512450300203',
    projectId: 'nhom4-ec8af',
    storageBucket: 'nhom4-ec8af.firebasestorage.app',
    androidClientId: '512450300203-n7qnqoso3hcm8cut4odu92428m202dtv.apps.googleusercontent.com',
    iosClientId: '512450300203-mf6nt69gc7lfch8shquhue5oltdchnqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhom4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQlR2TpMPSHlhRl4kU42vq0Fke3ATEaTI',
    appId: '1:512450300203:web:40044057b63d8d975c5d6e',
    messagingSenderId: '512450300203',
    projectId: 'nhom4-ec8af',
    authDomain: 'nhom4-ec8af.firebaseapp.com',
    storageBucket: 'nhom4-ec8af.firebasestorage.app',
  );

}